[tools]
btop = "latest"
bun = "latest"
cloudflared = "latest"
fastfetch = "latest"
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
gh = "latest"
"github:aria2/aria2" = "latest"
"github:ekzhang/bore" = "latest"
glab = "latest"
glow = "latest"
go = "latest"
herdr = "latest"
jq = "latest"
node = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@opencode-ai/cli" = { version = "beta", allow_builds = true }
python = "latest"
rclone = "latest"
ripgrep = "latest"
starship = "latest"
uv = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }

