[bootstrap.packages]
"apt:build-essential" = "latest"
"apt:curl" = "latest"
"apt:fish" = "latest"
"apt:git" = "latest"
"apt:git-lfs" = "latest"
"apt:openssh-client" = "latest"
"brew:wget" = "latest"
"brew:aria2" = "latest"
"brew:expect" = "latest"
"brew:nano" = "latest"
"brew:tree" = "latest"
"brew:unzip" = "latest"
"brew:zip" = "latest"
"pacman:base" = "latest"
"pacman:base-devel" = "latest"
"pacman:curl" = "latest"
"pacman:git" = "latest"
"pacman:git-lfs" = "latest"
"pacman:grep" = "latest"
"pacman:fish" = "latest"
"pacman:openssh" = "latest"
"pacman:sudo" = "latest"

[bootstrap.user]
login_shell = "/usr/bin/fish"

[tools]
btop = "latest"
tmux = "latest"
vim = "latest"
cloudflared = "latest"
fastfetch = "latest"
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
gh = "latest"
"github:ekzhang/bore" = "latest"
glab = "latest"
glow = "latest"
go = "latest"
herdr = "latest"
jq = "latest"
mitmproxy = "latest"
node = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@opencode-ai/cli" = { version = "beta", allow_builds = true }
pipx = "latest"
"pipx:google-colab-cli" = "latest"
python = "latest"
rclone = "latest"
ripgrep = "latest"
starship = "latest"
turso = "latest"
uv = "latest"
wrangler = { version = "latest", allow_builds = ["esbuild", "sharp", "workerd"] }
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
"pipx:speedtest-cli" = "latest"
"npm:agent-browser" = "latest"
bun = "latest"
"github:can1357/oh-my-pi" = "latest"
neonctl = "latest"

[settings]
minimum_release_age = "0"
auto_update = true
experimental = true

[settings.age]

[shell_alias]
cr = "chezmoi re-add"
cu = "chezmoi update"

[env]
CLOUDFLARE_ACCOUNT_ID = "13e8f6d8fb7367570ada75fa71e1999d"
CLOUDFLARE_API_TOKEN = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdNeTVjdyBUMHhNS0JtdFp1dHl1NG9jMVZNRjlJYnM4bnhIaTgzVjNVWjRkMU15QmxZCk53a2tHeHFubjQ5UzFqamN0MnBzQkZTZ05ON2JudlFkMjhOVzFMZG5selkKLT4gU259aShcPSQtZ3JlYXNlICo0V3ZVJ3hEClUzVGhWekZtdS9NS2lTOU9scHlId1RFYjQ3ODRiN2pCVlBYVWtBCi0tLSBvekNxUjdrZnVwNUpLRVRNbHFSOVRGSlZZVzJIS2xGYWxOejdKUVVKV3hVCnVIkVvvQK/irMaYSAnebrJRSgK4hsZCScLbSFzET7ny8NeFMOT1lswhBij8lQFA9/6UbTwRQCusk0SHRgeIo6q6NhcUAydGYz+OfxXXmZaHaJLKV+E" }
NEON_API_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdNeTVjdyAwWFFiTWpyZEg5K1ZrMSthUUV3R1o0VUdnWXYyUzJzQVpHek5rK1B4K0ZJCk04bUpGMVBzWWREaytSL2JPN3JiQm9XYzQyK0VLdFlZUHluUUJ6ZVBPM0UKLT4gKnlRXHs2Y3gtZ3JlYXNlICtMS1s2UUEgVHpZIiB1CnNQODl2dHEvc0s2VDVGeWRYVERLWDBDVm15WkxxQQotLS0gNExaaUlhMVFMZmlTWXFxS3VvZVZDL3daMlVDMUR6VnlZMzdsUllKd3l6dwpFfmB4FRRyIexZPUoEVcaYfAJkOORnznajeLw26lSzEFCwJ2wOzjR7xk15jW2lh7LyrDz+ItRPEvfv2+hhod/gpol1uHjN2n9w76jKrikpF2KtgPeZKlZ1dt8knzdspj+R8zeu0g" }
TURSO_AUTH_TOKEN = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDdNeTVjdyBiYzEvSUpveElzVjVscXdMZDUwZlFmek9iTVljQ0xSSlNiR3U1VVM1dkd3ClhPdDhXajhtNG5YRFRsUDMxQVhJcDMwSkp4ZzJsV0NXWm1DbXJBREpjTjgKLT4gZnxvLWdyZWFzZQozWFJPR0puWmQybEtSbmFlUnkrNE5uNmFyWWRJY3JnQ21UckFwVEFjMmNYL0syWjZ5VjJ4R0o5ek1VaWR1MUZPClRESU5uYkFpSmJWKzBrU1dLSzIybFRMYwotLS0gNVJLNXBoZEl2eHJIUlF2b0U3NnphcE1PWkVlaWtyQnk3Ri9NWUNPRFhmUQrx3HOABSGhQB46VGPw4VVu1kGqjQISHRsKG9zVb+jvMdybeXAKKtdvsXJWGHVhza9eotknFxd4uwH9/JgiXMTRrNMrVeADdZrwEHjf6iq7He6eYW2RghSocEwQ+RPR8l78LbKE4SZxXvhyxB5NPJDm6lZZCDSEoKY+xb06Z+2W2Mnc7xUFCxm2uspelNtLebXd0MeLZQi/N9xTjvNfP+EE+XsDUslxZ5MyaCyvJ59nZlK5wy+XAr8nmFY/7/GOhXkxBlQXgjIKbrZNlTjAsAz+X5o06rx/Y65HbLzF5xzNohFufXZAvDuxn53HcKcJ4iBrwvEY0+pQrjEJVwewfBfGXUiXUlr/fsQwxKip1yb3IF27oYJUnXEP/SxJnFJjAs6klG1hChjprLWm7anT7CAS0ewECbK9sJ8CqZZ849ySEVaJCgCDfiramCwarrVE1HosU2jPvH3bnVp+ZdP3niMLkHRSALdZqpR8dRZiwRz3u9bMRB8nUGGWc5gq6w" }
TURSO_DATABASE_URL = "libsql://crud-api-db-sachnun.aws-ap-northeast-1.turso.io"
